### ISSUE TITLE
Kind of bootloop

### ISSUE THREAD

**Issue by Yoanndp** [Magisk-Modules-Repo/FDE#1]
Hello, 

I just installed the module and my device booted up correctly.

But, after the module has been loaded (when FDE.AI toast notification appears), my phone reboot.

[FDE.AI logs](https://pastebin.com/raw/mSPDBPMW)

**Comment by feravolt** [comment]
> Hello,
> I just installed the module and my device booted up correctly.
> But, after the module has been loaded (when FDE.AI toast notification appears), my phone reboot.
> [FDE.AI logs](https://pastebin.com/raw/mSPDBPMW)
Hello. There is such problem on some rare Huawei devices - reason is still unknown. I hope in v5.0 this will be fixed.

**Comment by Aytackydln** [comment]
This issue still persists. As far as i know hotplug governor causes this.

**Comment by feravolt** [comment]
> This issue still persists. As far as i know hotplug governor causes this.

Will check that once again. Thanks.
