### ISSUE TITLE
What is the difference between this FDE and https://github.com/feravolt/FeraDroid-Engine?

### ISSUE THREAD

**Issue by zaoqi** [Magisk-Modules-Repo/FDE#2]
@feravolt

**Comment by mirsella** [comment]
the link you post is the personal GitHub of the creator, and here a duplication to be in the magisk module list

**Comment by feravolt** [comment]
Difference is in installer script. The one here is auto-replaced by Magisk & used only for Magisk. In personal repo - installer is universal for Magisk, SuperSU, init.d ..etc.
