### ISSUE TITLE
[Moderation] GPL Conformance

### ISSUE THREAD

**Issue by topjohnwu** [Magisk-Modules-Repo/FDE#3]
We have noticed that while your module is licensed as GPL, no source code is provided.
Please comply to the license and release the source code within 7 days, or else we will have to remove your module.

Please do note that simply relicensing your current module with another license does not work, this is not how open source license works. Relicensing the module now does not remove the fact that you have released numerous versions of your module violating the license.

I will personally give you a pass and allow your module to still be online if you release the source code of your *current* release, you don't have to provide the whole history of your source code. But please do note that only doing so is *still* not perfectly legal in terms of GPL, this is simply my personal mercy.

**Comment by feravolt** [comment]
Will do.

**Comment by TjReiny** [comment]
and we will remove GPL directly afterwards. there is no need to be GPL. we have no sources of FDE on github (yet).

**Comment by feravolt** [comment]
> We have noticed that while your module is licensed as GPL, no source code is provided.
> Please comply to the license and release the source code within 7 days, or else we will have to remove your module.
> 
> Please do note that simply relicensing your current module with another license does not work, this is not how open source license works. Relicensing the module now does not remove the fact that you have released numerous versions of your module violating the license.
> 
> I will personally give you a pass and allow your module to still be online if you release the source code of your _current_ release, you don't have to provide the whole history of your source code. But please do note that only doing so is _still_ not perfectly legal in terms of GPL, this is simply my personal mercy.

Please reply to me in telegram. Thx.
